package compiler

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/Nehonix-Team/xru/internal/engine"
)

var colorRegex = regexp.MustCompile(`</?([a-zA-Z]+|)>`)

// CompileToSH converts an XRU RuleFile into a standalone Shell script.
func CompileToSH(rf *engine.RuleFile) (string, error) {
	var sb strings.Builder
	sb.WriteString("#!/bin/sh\n")
	sb.WriteString("# Generated by XRU Compiler — Standalone Mode\n\n")
	sb.WriteString("set -e\n\n")

	for _, rule := range rf.Rules {
		err := transpileRuleSH(&sb, rule)
		if err != nil {
			return "", err
		}
	}

	return sb.String(), nil
}

func transpileRuleSH(sb *strings.Builder, rule engine.Rule) error {
	switch rule.Type {
	case engine.RuleTypeVar:
		sb.WriteString(fmt.Sprintf("%s=\"%s\"\n", rule.Target, shellInterpolate(shellEscape(rule.Content))))
	case engine.RuleTypeSelect:
		sb.WriteString(fmt.Sprintf("cd \"%s\" || exit 1\n", shellInterpolate(rule.Target)))
	case engine.RuleTypeModule:
		parts := strings.SplitN(rule.Target, ".", 2)
		if len(parts) < 2 {
			return nil
		}
		mod, method := strings.ToLower(parts[0]), strings.ToUpper(parts[1])
		if mod == "utils" || mod == "u" {
			if method == "LOG" {
				cleanMsg := stripColors(rule.Content)
				sb.WriteString(fmt.Sprintf("echo \"%s\"\n", shellInterpolate(cleanMsg)))
			}
		} else if mod == "sys" || mod == "s" {
			if method == "EXEC" {
				if rule.As != "" {
					sb.WriteString(fmt.Sprintf("%s=$(%s)\n", rule.As, shellInterpolate(rule.Content)))
				} else {
					sb.WriteString(fmt.Sprintf("%s\n", shellInterpolate(rule.Content)))
				}
			}
		}
	case engine.RuleTypeCreate:
		sb.WriteString(fmt.Sprintf("mkdir -p \"$(dirname \"%s\")\"\n", shellInterpolate(rule.Target)))
		sb.WriteString(fmt.Sprintf("cat << 'EOF' > \"%s\"\n%sEOF\n", shellInterpolate(rule.Target), rule.Content))
	case engine.RuleTypeBegin:
		sb.WriteString(fmt.Sprintf("# Warning: Structural patching for %s requires xru binary\n", rule.Target))
		sb.WriteString(fmt.Sprintf("echo \"[SKIP] Structural patching for %s is not supported in pure SH\"\n", rule.Target))
	}
	return nil
}

// CompileToPS1 converts an XRU RuleFile into a standalone PowerShell script.
func CompileToPS1(rf *engine.RuleFile) (string, error) {
	var sb strings.Builder
	sb.WriteString("# Generated by XRU Compiler — Standalone Mode\n")
	sb.WriteString("$ErrorActionPreference = 'Stop'\n\n")

	for _, rule := range rf.Rules {
		err := transpileRulePS1(&sb, rule)
		if err != nil {
			return "", err
		}
	}

	return sb.String(), nil
}

func transpileRulePS1(sb *strings.Builder, rule engine.Rule) error {
	switch rule.Type {
	case engine.RuleTypeVar:
		sb.WriteString(fmt.Sprintf("$%s = \"%s\"\n", rule.Target, psInterpolate(shellEscape(rule.Content))))
	case engine.RuleTypeSelect:
		sb.WriteString(fmt.Sprintf("Set-Location \"%s\"\n", psInterpolate(rule.Target)))
	case engine.RuleTypeModule:
		parts := strings.SplitN(rule.Target, ".", 2)
		if len(parts) < 2 {
			return nil
		}
		mod, method := strings.ToLower(parts[0]), strings.ToUpper(parts[1])
		if mod == "utils" || mod == "u" {
			if method == "LOG" {
				cleanMsg := stripColors(rule.Content)
				sb.WriteString(fmt.Sprintf("Write-Host \"%s\"\n", psInterpolate(cleanMsg)))
			}
		} else if mod == "sys" || mod == "s" {
			if method == "EXEC" {
				if rule.As != "" {
					sb.WriteString(fmt.Sprintf("$%s = & %s\n", rule.As, psInterpolate(rule.Content)))
				} else {
					sb.WriteString(fmt.Sprintf("& %s\n", psInterpolate(rule.Content)))
				}
			}
		}
	case engine.RuleTypeCreate:
		sb.WriteString(fmt.Sprintf("New-Item -Path \"%s\" -ItemType File -Force\n", psInterpolate(rule.Target)))
		sb.WriteString(fmt.Sprintf("Set-Content -Path \"%s\" -Value @'\n%s'@\n", psInterpolate(rule.Target), rule.Content))
	}
	return nil
}

func shellEscape(s string) string {
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

func shellInterpolate(s string) string {
	return strings.NewReplacer("{", "${", "}", "}").Replace(s)
}

func psInterpolate(s string) string {
	return strings.NewReplacer("{", "$", "}", "").Replace(s)
}

func stripColors(s string) string {
	return colorRegex.ReplaceAllString(s, "")
}
