# Generated by XRU Compiler — Standalone Mode (Windows)
$ErrorActionPreference = 'Stop'

$project_name = "XyPriss Demo"
$target_dir = "demo_project"
Write-Host "[INIT] Starting Full Syntax Test for $project_name"
Set-Location "$target_dir"
Write-Host "  → Sandbox set to: $ROOT"
Write-Host "  [SUB CHECK] Variable from sub: $sub_var"
New-Item -Path "docs/README.md" -ItemType File -Force
Set-Content -Path "docs/README.md" -Value @'
    # Documentation for {project_name}
    Created by XRU Full Syntax Test.
    Base: {ROOT}
'@
$DOC_LIST = & ls -R docs
Write-Host "  [FILESYSTEM] Docs created:\n$DOC_LIST"
Write-Host "\n[SUCCESS] Full Syntax Test completed for $project_name!"
