package sh

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/Nehonix-Team/xru/internal/engine/ast"
)

var colorRegex = regexp.MustCompile(`</?([a-zA-Z]+|)>`)

// Compile converts an XRU RuleFile into a standalone Shell script.
func Compile(rf *ast.RuleFile) (string, error) {
	var sb strings.Builder
	sb.WriteString("#!/bin/sh\n")
	sb.WriteString("# Generated by XRU Compiler — Standalone Mode (Unix)\n\n")
	sb.WriteString("set -e\n\n")

	for _, rule := range rf.Rules {
		err := transpileRule(&sb, rule)
		if err != nil {
			return "", err
		}
	}

	return sb.String(), nil
}

func transpileRule(sb *strings.Builder, rule ast.Rule) error {
	switch rule.Type {
	case ast.RuleTypeVar:
		sb.WriteString(fmt.Sprintf("%s=\"%s\"\n", rule.Target, interpolate(escape(rule.Content))))
	case ast.RuleTypeSelect:
		sb.WriteString(fmt.Sprintf("cd \"%s\" || exit 1\n", interpolate(rule.Target)))
	case ast.RuleTypeModule:
		parts := strings.SplitN(rule.Target, ".", 2)
		if len(parts) < 2 {
			return nil
		}
		mod, method := strings.ToLower(parts[0]), strings.ToUpper(parts[1])
		if mod == "utils" || mod == "u" {
			if method == "LOG" {
				cleanMsg := stripColors(rule.Content)
				sb.WriteString(fmt.Sprintf("echo \"%s\"\n", interpolate(cleanMsg)))
			}
		} else if mod == "sys" || mod == "s" {
			if method == "EXEC" {
				if rule.As != "" {
					sb.WriteString(fmt.Sprintf("%s=$(%s)\n", rule.As, interpolate(rule.Content)))
				} else {
					sb.WriteString(fmt.Sprintf("%s\n", interpolate(rule.Content)))
				}
			}
		}
	case ast.RuleTypeCreate:
		sb.WriteString(fmt.Sprintf("mkdir -p \"$(dirname \"%s\")\"\n", interpolate(rule.Target)))
		sb.WriteString(fmt.Sprintf("cat << 'EOF' > \"%s\"\n%sEOF\n", interpolate(rule.Target), rule.Content))
	case ast.RuleTypeBegin:
		sb.WriteString(fmt.Sprintf("# Warning: Structural patching for %s requires xru binary\n", rule.Target))
		sb.WriteString(fmt.Sprintf("echo \"[SKIP] Structural patching for %s is not supported in pure SH\"\n", rule.Target))
	}
	return nil
}

func escape(s string) string {
	return strings.ReplaceAll(s, "\"", "\\\"")
}

func interpolate(s string) string {
	return strings.NewReplacer("{", "${", "}", "}").Replace(s)
}

func stripColors(s string) string {
	return colorRegex.ReplaceAllString(s, "")
}
