#!/bin/sh
# Generated by XRU Compiler — Standalone Mode (Unix)

set -e

project_name="XyPriss Demo"
target_dir="demo_project"
echo "[INIT] Starting Full Syntax Test for ${project_name}"
cd "${target_dir}" || exit 1
echo "  → Sandbox set to: ${ROOT}"
echo "  [SUB CHECK] Variable from sub: ${sub_var}"
mkdir -p "$(dirname "docs/README.md")"
cat << 'EOF' > "docs/README.md"
    # Documentation for {project_name}
    Created by XRU Full Syntax Test.
    Base: {ROOT}
EOF
# Warning: Structural patching for config.json requires xru binary
echo "[SKIP] Structural patching for config.json is not supported in pure SH"
DOC_LIST=$(ls -R docs)
echo "  [FILESYSTEM] Docs created:\n${DOC_LIST}"
# Warning: Structural patching for src/main.ts requires xru binary
echo "[SKIP] Structural patching for src/main.ts is not supported in pure SH"
# Warning: Structural patching for config.json requires xru binary
echo "[SKIP] Structural patching for config.json is not supported in pure SH"
echo "\n[SUCCESS] Full Syntax Test completed for ${project_name}!"
