# Generated by XRU Compiler — Standalone Mode (Windows)
$ErrorActionPreference = 'Stop'

$app_name = "XyPriss"
$rel = "file.md"
Set-Location "apps/$app_name"
Write-Host "[INFO] Traitement de $app_name dans $ROOT\n"
Write-Host "\n[SUCCESS] Transformation finished for $app_name"
Write-Host "[EXPECTED ERROR] Scoped variable check: $theme"
