#!/bin/sh
# Generated by XRU Compiler — Standalone Mode (Unix)

set -e

app_name="XyPriss"
rel="file.md"
cd "apps/${app_name}" || exit 1
echo "[INFO] Traitement de ${app_name} dans ${ROOT}\n"
# Warning: Structural patching for config.json requires xru binary
echo "[SKIP] Structural patching for config.json is not supported in pure SH"
echo "\n[SUCCESS] Transformation finished for ${app_name}"
echo "[EXPECTED ERROR] Scoped variable check: ${theme}"
